[project]
name = "mcduck-finance"
version = "0.1.0"
description = "Scrooge McDuck is a financial management API designed to help users gain full control over their personal or business finances."
readme = "README.md"
requires-python = ">=3.14"
dependencies = []
